### ISSUE TITLE
Uncaught TypeError: editor.displayBuffer.getScrollTop is not a function

### ISSUE THREAD

**Issue by amkarthik** [ranjitjhala/hover-tooltips-liquid#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Linux Mint
**Thrown From**: [hover-tooltips-liquid](https://github.com/ranjitjhala/hover-tooltips-liquid) package, v0.7.0
### Stack Trace

Uncaught TypeError: editor.displayBuffer.getScrollTop is not a function

```
At /home/harmony-12/.atom/packages/hover-tooltips-liquid/node_modules/hover-tooltips/lib/hover-tooltips.js:53

TypeError: editor.displayBuffer.getScrollTop is not a function
  at showExpressionType (/home/harmony-12/.atom/packages/hover-tooltips-liquid/node_modules/hover-tooltips/lib/hover-tooltips.js:53:49)
  at /home/harmony-12/.atom/packages/hover-tooltips-liquid/node_modules/hover-tooltips/lib/hover-tooltips.js:40:63

```
### Commands

```
     -2:53.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-pylint",
      "linter-tidy",
      "minimap-codeglance"
    ],
    "ignoredNames": [
      ".pyc",
      ".project",
      ".pydevproject"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
bottom-dock, v0.3.5
hover-tooltips-liquid, v0.7.0
linter, v1.10.0
linter-csslint, v1.1.0
linter-js-yaml, v1.2.0
linter-jshint, v1.2.1
linter-jsonlint, v1.0.1
linter-manager, v0.2.6
linter-shellcheck, v1.0.2
minimap, v4.16.0
minimap-autohide, v0.10.1
minimap-find-and-replace, v4.3.2
minimap-linter, v1.0.0
spell-check, v0.62.0

# Dev
No dev packages
```

**Comment by ranjitjhala** [comment]
Thanks for the heads up! Will upgrade hover-tooltips dependency which fixes this problem, as soon as at real computer!

**Comment by ranjitjhala** [comment]
Fixed in new version, please upgrade, thanks!
